version: "3"
networks:
  default:
  py2:
volumes:
  postgres-db-volume:

services:
  ckan-postgres-2:
    networks:
      py2:
        aliases:
          - ckan-postgres
    image: "postgres:10"
    environment:
      POSTGRES_USER: ckan
      POSTGRES_PASSWORD: ckan

  ckan-postgres:
    networks:
      - default
    image: "postgres:10"
    environment:
      POSTGRES_USER: ckan
      POSTGRES_PASSWORD: ckan

  ckan-redis-2:
    networks:
      py2:
        aliases:
          - ckan-redis
    image: "redis:3"

  ckan-redis:
    networks:
      - default
    image: "redis:3"

  ckan-py3:
    image: python:3-stretch
    networks:
      - default

    environment:
      HOME: /usr/src
      CKAN_DATASTORE_POSTGRES_DB: datastore_test
      CKAN_DATASTORE_POSTGRES_READ_USER: datastore_read
      CKAN_DATASTORE_POSTGRES_READ_PWD: pass
      CKAN_DATASTORE_POSTGRES_WRITE_USER: datastore_write
      CKAN_DATASTORE_POSTGRES_WRITE_PWD: pass
      CKAN_POSTGRES_DB: ckan_test
      CKAN_POSTGRES_USER: ckan_default
      CKAN_POSTGRES_PWD: pass
      PGPASSWORD: ckan
      PYTEST_COMMON_OPTIONS: -v --ckan-ini=test-core-circle-ci.ini --cov=ckan --cov=ckanext --junitxml=~/junit/junit.xml
    working_dir: "/usr/src"
    volumes:
      - "../:/usr/src"
    command:
      ['tail', '-f', '/etc/debian_version']

  ckan-py2:
    image: python:2-stretch
    networks:
      - py2
    environment:
      HOME: /usr/src
      CKAN_DATASTORE_POSTGRES_DB: datastore_test
      CKAN_DATASTORE_POSTGRES_READ_USER: datastore_read
      CKAN_DATASTORE_POSTGRES_READ_PWD: pass
      CKAN_DATASTORE_POSTGRES_WRITE_USER: datastore_write
      CKAN_DATASTORE_POSTGRES_WRITE_PWD: pass
      CKAN_POSTGRES_DB: ckan_test
      CKAN_POSTGRES_USER: ckan_default
      CKAN_POSTGRES_PWD: pass
      PGPASSWORD: ckan
      PYTEST_COMMON_OPTIONS: -v --ckan-ini=test-core-circle-ci.ini --cov=ckan --cov=ckanext --junitxml=~/junit/junit.xml
    working_dir: "/usr/src"
    volumes:
      - "../:/usr/src"
    command:
      ['tail', '-f', '/etc/debian_version']
